{% set version = "0.9.1" %}

package:
  name: qgnomeplatform
  version: {{ version }}

source:
  url: https://github.com/FedoraQt/qgnomeplatform/archive/{{ version }}.tar.gz
  sha256: f85e0aa521c3e2f7f59a0fe98360fae30acd02b6940af9e86b4db9c17e02e807

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - qt-main                            # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  host:
    - qt-main
    - qt-wayland
    - adwaita-qt
    - gsettings-desktop-schemas
    - gtk3
    - gdk-pixbuf
    - pango
    - glib
    - xorg-libxrandr
    - xorg-libxcursor
    - xorg-libxcomposite
    - xorg-libxdamage
    - xorg-libxinerama
    - xorg-xineramaproto

test:
  commands:
    - test -f "${PREFIX}/plugins/platformthemes/libqgnomeplatformtheme.so"
    - test -f "${PREFIX}/lib/libqgnomeplatform.so"
    - test -f "${PREFIX}/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so"

about:
  home: https://github.com/FedoraQt/QGnomePlatform
  summary: QGnomePlatform is a Qt Platform Theme designed to use as many of the GNOME settings as possible in unmodified Qt applications.
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
