{% set version = "0.9.2" %}

package:
  name: qgnomeplatform
  version: {{ version }}

source:
  url: https://github.com/FedoraQt/qgnomeplatform/archive/{{ version }}.tar.gz
  sha256: 9446c0d68faccdd0e44039b2089ab4524939a47cfe8c34e50b0368c2b58a5552
  patches:
    - correct_install_path.patch
    # Update 2023/09/10 I am about 90% sure that this was a bug in Ubuntu 23.04
    # and that it is resolved in 23.10
    # 2023/07 hmaarrfk
    # I think there is a bug in ubuntu with XDG-Desktop-Portal
    # I worked with QGnomePlatform
    # https://github.com/FedoraQt/QGnomePlatform/issues/146
    # To get to the bottom of it
    # but it seems that it is either a work in progress
    # or still an active bug
    # https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal-gnome/+bug/2013116
    # In either case because there are other pure GTK dialogs just below the logic
    # in the source, I'm going to patch this out in order to provide users with
    # a better experience until further notice.
    # - force_gtk_native_dialogis_not_xdg.patch

build:
  skip: true  # [not linux]
  number: 1

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - qt-main                            # [build_platform != target_platform]
    - sysroot_linux-64 2.17              # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl') }}           # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libglvnd-egl') }}          # [linux]
  host:
    - qt-main
    - qt-wayland
    - adwaita-qt
    - gsettings-desktop-schemas
    - gtk3
    - gdk-pixbuf
    - pango
    - glib
    - xorg-libxrandr
    - xorg-libxcursor
    - xorg-libxcomposite
    - xorg-libxdamage
    - xorg-libxinerama
    - xorg-xineramaproto

test:
  commands:
    - test -f "${PREFIX}/plugins/platformthemes/libqgnomeplatformtheme.so"
    - test -f "${PREFIX}/lib/libqgnomeplatform.so"
    - test -f "${PREFIX}/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so"

about:
  home: https://github.com/FedoraQt/QGnomePlatform
  summary: QGnomePlatform is a Qt Platform Theme designed to use as many of the GNOME settings as possible in unmodified Qt applications.
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
